one catch

diff --git a/.github/workflows/cml.yaml b/.github/workflows/cml.yaml
--- a/.github/workflows/cml.yaml
+++ b/.github/workflows/cml.yaml
@@ -44,8 +44,8 @@ jobs:
             git push 
             dvc push
 
-            echo 'commited'
-          ) || (
+            echo 'commited?'
+      
             # Use DVC metrics diff to compare metrics to master
             dvc metrics diff --show-md master >> report.md
             
@@ -53,5 +53,5 @@ jobs:
             dvc plots diff --target loss.csv --show-vega master > vega.json
             vl2png vega.json -s 1.3 | cml-publish --md >> report.md
             cml-send-comment report.md 
-          )
+          ) || echo 'failed doing commit, is there something to commit?'
           
